version: "2"

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: error-strings
      - name: unused-parameter

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - bodyclose
    - misspell
    - unconvert
    - unparam

issues:
  exclude-rules:
    - source: "fmt\\.Fprint"
      linters:
        - errcheck
    - linters:
        - revive
      text: "(should have a package comment|exported .* should have comment)"

run:
  timeout: 5m
